openapi: 3.0.0
info:
  title: Shipping Portal API
  description: documentation for apis about shipping data.
  version: 2.3.3
servers:
  - url: https://chaoscybercats-warehouse-automation-function.azurewebsites.net/api/
    description: development server
  - url: http://localhost:3000
    description: localhost port
paths:
  /add_shipping_data:
    post:
      security:
          - ApiKeyAuth: []
      summary: add a bunch of shipping data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/post_shipping_item'
      responses:
        '200':
          description: you know what you are doing!
        '114514':
          description: what are u doing?
  /shipping_data:
    get:
      security:
        - ApiKeyAuth: []
      summary: Returns a list of shipping data.
      parameters:
        - in: query
          name: shipperid
          schema:
            type: string
          required: true  
          examples:       # Multiple examples
            default:         # Distinct name
              value: tako0    # Example value
              summary: tako  # Optional description
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: object
                $ref: '#/components/schemas/get_shipping_item'
components:
  schemas:
    shipping_item:
      type: object
      properties:
        id:
          type: string
          example: 1
        Date:
          type: string
          example: Wah 0, 2222
        ShipmentID:
          type: string
          example: 0
        ShipperID:
          type: string
          example: tako
        WarehouseID:
          type: string
          example: 0
        BoxesRcvd:
          type: string
          example: 0
        ShippingPO:
          type: string
          example: 0
    get_shipping_item:
      type: array
      items:
        type: object
        $ref: '#/components/schemas/shipping_item'
    post_shipping_item:
      type: object
      properties:
        Received: 
          type: array
          items:
            type: object
            $ref: '#/components/schemas/shipping_item'
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: x-functions-key  # name of the header, query parameter or cookie
# 2) Apply the API key globally to all operations
security:
  - ApiKeyAuth: []     # use the same name as under securitySchemes