openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: https://chaoscybercats-warehouse-automation-function.azurewebsites.net/api/
    description: development server
  - url: http://localhost:3000
    description: localhost port
paths:
  /shipping_data:
    get:
      security:
        - ApiKeyAuth: []
      summary: Returns a list of shipping data.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: query
          name: shipperid
          schema:
            type: string
          required: true  
          examples:       # Multiple examples
            default:         # Distinct name
              value: tako0    # Example value
              summary: tako0  # Optional description
            
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: x-functions-key  # name of the header, query parameter or cookie
# 2) Apply the API key globally to all operations
security:
  - ApiKeyAuth: []     # use the same name as under securitySchemes